### ISSUE TITLE
Can I get checkpoints and datasets?

### ISSUE THREAD

**Issue by LeeDongYeun** [kaist-siit-lab/StarLab_1-1#1]
Hello,

Thank you for your work on this amazing project! I am very interested in testing and learning more from it. However, I noticed that the documentation does not include information on where to find the necessary checkpoints and datasets to run the model.

Could you please provide information on:

1. Pre-trained checkpoints: Are these available for download? If yes, could you share the links or instructions to access them?
2. Datasets: Are the datasets used in this project publicly available? If so, could you share where to obtain them or provide details on their structure?

Your help would be greatly appreciated, and I believe this will also benefit other users who wish to explore the project further.

Thank you for your time and support!

Best regards

**Comment by koooooooook** [comment]
Thank you for your interest!

We'll be releasing it soon, and we will provide generated latent vectors for reproducing results.

**Comment by koguma00** [comment]
Thank you for your interest!

We'll be releasing it soon, and we will provide generated latent vectors for reproducing results.
