### ISSUE TITLE
Could you explain about create_mesh?

### ISSUE THREAD

**Issue by jaemyung-u** [kaist-siit-lab/StarLab_1-1#8]
Could you explain about create_mesh?

**Comment by koguma00** [comment]
It creates a 3D mesh using a Signed Distance Function (SDF) predicted by a decoder. The function create_mesh:
Samples a 3D grid of points in space (voxels) within a unit cube.
Uses a neural network decoder to predict SDF values at these points.
Converts the SDF grid into a 3D mesh (e.g., saved as a .ply file).
